/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
    "./types/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        // Common healthcare/medical colors
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          500: '#f59e0b',
          600: '#d97706',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          500: '#ef4444',
          600: '#dc2626',
        }
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      }
    },
  },
  plugins: [],
  // Ensure all classes are generated for production
  safelist: [
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-500',
    'bg-gray-600',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'text-white',
    'text-black',
    'border-gray-200',
    'border-gray-300',
    'border-gray-400',
    'border-gray-500',
    'bg-white',
    'bg-blue-50',
    'bg-blue-100',
    'bg-blue-500',
    'bg-blue-600',
    'bg-green-50',
    'bg-green-100',
    'bg-green-500',
    'bg-red-50',
    'bg-red-100',
    'bg-red-500',
    'bg-yellow-50',
    'bg-yellow-100',
    'bg-yellow-500',
    'text-blue-600',
    'text-green-600',
    'text-red-600',
    'text-yellow-600',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-blue-600',
    'hover:bg-green-600',
    'hover:bg-red-600',
    'focus:ring-blue-500',
    'focus:border-blue-500',
    'rounded',
    'rounded-md',
    'rounded-lg',
    'shadow',
    'shadow-md',
    'shadow-lg',
    'p-2',
    'p-3',
    'p-4',
    'px-2',
    'px-3',
    'px-4',
    'py-1',
    'py-2',
    'py-3',
    'm-2',
    'm-4',
    'mb-2',
    'mb-4',
    'mt-2',
    'mt-4',
    'w-full',
    'w-auto',
    'h-full',
    'h-auto',
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'justify-between',
    'space-x-2',
    'space-x-4',
    'space-y-2',
    'space-y-4'
  ]
} 